[versions]
assertj = "3.23.1"
findbugs = "3.0.1"
jackson = "2.14.2"
jooq = "3.16.14"
junit = "4.13.2"
log4j = "2.19.0"
micrometer = "1.10.0"
mockito = "3.12.4"
slf4j = "1.7.36"
sqlite = "3.41.2.2"
typesafe-config = "1.4.2"
snakeyaml = "2.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
findbugs-annotations = { module = "com.google.code.findbugs:annotations", version.ref = "findbugs" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
junit = { module = "junit:junit", version.ref = "junit" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
micrometer = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }


[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
javadocLinks = { id = "io.github.sgtsilvio.gradle.javadoc-links", version = "0.8.0" }
mavenCentralPublishing = { id = "io.github.sgtsilvio.gradle.maven-central-publishing", version = "0.4.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.1.13" }